name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests (optional)
      run: |
        pytest  # Run tests here if you have any

    - name: Run Streamlit app
      run: |
        streamlit run app.py
